backend:
  name: github
  repo: NikosKourkoulos1/panostsomakos-portfolio  # Your GitHub repo
  branch: master
  auth_type: implicit  # Required for Netlify
  app_id: $GITHUB_CLIENT_ID  # Netlify env variable
  base_url: https://git-gateway.netlify.app  # Critical for Netlify

media_folder: "src/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Order", name: "order", widget: "number", default: 0 }
      - { label: "Tags", name: "tags", widget: "list", default: ["projects"] }
      - {
          label: "Images",
          name: "images",
          widget: "list",
          field: { label: "Image", name: "image", widget: "image" }
        }
