backend:
  name: github
  repo: NikosKourkoulos1/panostsomakos-portfolio
  branch: master

media_folder: "src/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "test"
    label: "Test Content"
    folder: "src/test" # This folder doesn't have to exist for the CMS to load
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}